# Generated by Django 4.0.5 on 2022-06-12 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accolades', '0002_alter_profile_profile_pic_alter_project_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(upload_to='project-images/'),
        ),
    ]
