# Generated by Django 4.0.5 on 2022-06-14 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accolades', '0004_rates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rates',
            name='content_rate',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='rates',
            name='design_rate',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='rates',
            name='usability_rate',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
