# Generated by Django 4.0.5 on 2022-06-14 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accolades', '0006_remove_rates_content_average_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(default='default_ptavb7.png', upload_to='profile-images/'),
        ),
    ]
